
asyncapi: "3.0.0"
info:
  title: Common AsyncAPI components
  version: 1.0.0
components:
  messages:
    null:
      payload:
        type: "null"
    dada:
      payload:
        type: object
        properties:
          dada:
            type: string

  replyAddresses:
    std:
      location: "$message.header#reply-to"
  # operationTraits:
  #   std-req-reply:
  #     reply:
  #       $ref: "#/components/replyAddresses/std"
